name = "mail-app"
compatibility_date = "2025-09-24"

# 本地与生产均声明同名绑定；
# 本地开发使用 preview_id，Miniflare 会提供临时 KV。
[[kv_namespaces]]
binding = "MAIL_TOKENS"
id = "f3f8f398c29740b494a486c5729ff972"
preview_id = "f3f8f398c29740b494a486c5729ff972"

# Pages Functions 使用 app/_worker.js；静态资源为当前目录
# 无需设置 build 输出目录与命令

