name = "mail-viewer-api"
main = "index.js"
compatibility_date = "2024-01-01"
workers_dev = true

# 静态资源绑定（将 ../app 作为静态站点目录）
assets = { binding = "ASSETS", directory = "../app" }

# KV 命名空间绑定
kv_namespaces = [
  { binding = "MAIL_TOKENS", id = "your-kv-namespace-id" }
]

# 环境变量（管理员密码）
[vars]
# ADMIN_PASSWORD 将通过 secret 设置，不在这里明文配置

# 生产环境配置
[env.production]
name = "mail-viewer-api"
